{% set name = "duecredit" %}
{% set version = "0.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/duecredit-{{ version }}.tar.gz
  sha256: 7b5c1ae10927f9e02cf4d54e2c74a8aa00cd29c38d637defe3c948d3d8e9f33a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - duecredit = duecredit.cmdline.main:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.0.0
  run:
    - citeproc-py >=0.4
    - looseversion
    - packaging
    - python >={{ python_min }}
    - requests

test:
  imports:
    - duecredit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/duecredit/duecredit
  summary: Automated collection and reporting of citations for used software/methods/datasets
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yarikoptic
    - smoia
    - mscheltienne
