{% set name = "duecredit" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/duecredit-{{ version }}.tar.gz
  sha256: be5a787d35b1a44f1de27aa992c7cdda003e2fe4c0f451fae9a4cf5090de5050

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - duecredit = duecredit.cmdline.main:main

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=61.0.0
  run:
    - citeproc-py >=0.4
    - python >=3.8
    - requests

test:
  imports:
    - duecredit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/duecredit/duecredit
  summary: Automated collection and reporting of citations for used software/methods/datasets
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yarikoptic
    - smoia
    - mscheltienne
